### ISSUE TITLE
Problems in textbook

### ISSUE THREAD

**Issue by hyu45** [jhajek/Linux-text-book-part-1#13]
Hello Professor
How are you? We just find some problems in the textbook. The Chapter10's review questions match to Chapter11's answer, and Chapter 11's review questions match to Chapter12's answer. What's more, it seems like there's no match questions to the chapter10's answer. 

Take care

**Comment by jhajek** [comment]
thanks for the post.  I fixed appendix B upto ch. 11, check the release tab for the new version just built.  I will be adding ch 12 and 13 tonight.

**Comment by jhajek** [comment]
Will be fixed
