### ISSUE TITLE
Question regarding review question in chapter 7

### ISSUE THREAD

**Issue by albuic** [jhajek/Linux-text-book-part-1#4]
In chapter 7, one of the review question is : "What is the key you use in vi to transition between COMMAND MODE and INSERT mode? (Just three letters)"
And the answer is ESC but in reality, you cannot use ESC to go from Command mode to Insert mode.
The question should be : "What is the key you use in vi to transition form INSERT mode to COMMAND mode ? (Just three letters)"

**Comment by jhajek** [comment]
Yes, that would seem to be an error on my part...  I merged your pull request and updated the question -- keep up the good work
