### ISSUE TITLE
Fedora building instructions

### ISSUE THREAD

**Issue by psfales** [jhajek/Linux-text-book-part-1#42]
When attempting to build on Fedora 31 by following the instructions in README.md, I ran into these issues

- The prerequisite texlive-pdftex.noarch is not found.    I had to install texlive-pdftex.x86_64 (or more generally just "texlive-pdftex")

- My first attempt to build failed because rsvg2pdf is not found.   On a whim, I installed  librsvg2-tools.x86_64 and the build succeeded.  (I'm not sure why because there is still no rsvg2pdf command.  I haven't fully verified that the resulting pdf files are complete and correct, but they look OK from what I can see.)   It looks like librsvg-tools should be added the prerequisite list

**Comment by jhajek** [comment]
Good catch.  I made the suggested changes, updated the Readme.md  and tested it on an older Pandoc 2.2.2-1 and 2.9.1  and everything compiled and rendered correctly.   Also add your GitHub ID to section 1.2 (for those who contribute)
