### ISSUE TITLE
Typos in 12292019

### ISSUE THREAD

**Issue by psfales** [jhajek/Linux-text-book-part-1#43]
I found a number of typos when I read the book last fall.   I see that many of them have been fixed now, but these are still present in the 12292019 version

1.1 "In 1969, the first UNIX operating system was created by Bell Labs employees at AT&T. AT&T Bell Labs was spun off as part of Lucent Technology" should be "Lucent Technologies"

2.3.4.1 "The best demonstration of these tenants" should be "tenets"

2.5.5.2 Linus has returned to kernel development

3.5.1.1 "It comes as an add-on service component and is a fully functional implementation of the sever class product" should be "server"

4.7.1 "Hey its Windows, do they need a reason?"  should be "it's"

9.4.4 "systemd has preplaced syslog with journald" should be "replaced"

10.3.2 "There is a replacement in the works for GRUB called systemd-boot or also known as gummi-boot, which is German for "Inflatible boat" should be "Inflatable"

11.3.2 "SSDs do have potential issues with ware leveling and block failure," should be "wear leveling"

11.3.3 "There by eliminating potential system bottleneck and making the platform of memory a single platform." I think the word is "Thereby" but this really isn't a sentence and should probably be reworded.   The world "platform" is used twice.

**Comment by jhajek** [comment]
All are fixed -- thanks for catching these.

**Comment by psfales** [comment]
Incidentally... I think it's "Etsy F-S-tab"  :-)

-- 
Pete

**Comment by jhajek** [comment]
Ah yes, that was an old joke that Professor Sam used to tell.   He would intentionally mispronounce it, but I never understood why.
