### ISSUE TITLE
SVG Conversion issue

### ISSUE THREAD

**Issue by sonokamome** [jhajek/Linux-text-book-part-1#45]
When I tried to build this in **both** Windows or in Linux I've run to this very particular problem with the SVG asset used. A screenshot for review:
![WindowsTerminal_2020-06-17_02-13-12-1](https://user-images.githubusercontent.com/13297452/84879656-59404080-b040-11ea-920e-248aa0d0668b.png)

This results every format being outputted except the PDF document.
I just wanted to let you know this because I really did want to have this book in PDF format. I tried to figure out what exactly I could try to fix with the SVG graphic(s??) but I can't seem to figure out what it could be exactly. :shrug:

**Comment by jhajek** [comment]
Hi - thanks for this, I removed the offending SVG file from Chapter 2.  Now it should build without need the rsvg-convert library.
